import { Metadata } from "next";
import SideBar from "./ui/SideBar";
import SidebarItem from "./ui/SidebarItem";
import {
  Article,
  BarChart,
  EditNote,
  Help,
  PeopleRounded,
  PersonPinCircle,
  Settings,
} from "@mui/icons-material";

export const metadata: Metadata = {
  title: "Web Genius - Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex relative">
      <SideBar>
        <SidebarItem
          url="authors-requests"
          text="Authors requests"
          icon={<PersonPinCircle />}
        />
        <SidebarItem url="authors" text="Authors" icon={<PeopleRounded />} />
        <SidebarItem url="articles" text="Articles" icon={<Article />} />
        <SidebarItem url="creator" text="Ceator" icon={<EditNote />} />
        <hr className="my-3" />
        <SidebarItem url="settings" text="Settings" icon={<Settings />} />
        <SidebarItem url="help" text="Help" icon={<Help />} />
      </SideBar>
      <div className="w-full p-4">{children}</div>
    </div>
  );
}
