import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Web Genius - Account",
  description: "Generated by create next app",
};

export default function AccountLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="ideal-h p-4 my-0 mx-auto flex items-center justify-center">
      <img
        className="w-[434px] acc-cust-h object-cover"
        src={"/images/R.jpg"}
        alt="banner"
      />
      <div className="w-[434px] acc-cust-h p-4 flex flex-col items-center justify-center bg-slate-50  shadow-lg rounded">
        <div className="w-full">{children}</div>
      </div>
    </div>
  );
}
